#!/usr/bin/env python3
"""Generate lib/core/theme/app_colors.dart from the extracted design tokens.

The prototype expresses its palette as two CSS variable maps (DARK and LIGHT)
with identical keys. Transcribing 40 rgba() values by hand would guarantee
drift, so they are compiled instead. Re-run after changing the design.

Usage:  python3 tool/generate_theme.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, 'design', 'extracted', 'tokens.json')
OUT = os.path.join(ROOT, 'lib', 'core', 'theme', 'app_colors.dart')

# CSS variable -> (Dart name, doc comment)
NAMES = {
    '--bg':    ('background',      'App background, behind the screen surface.'),
    '--scr':   ('surface',         'The screen surface itself.'),
    '--g1':    ('glass',           'Glass fill -- the default card background.'),
    '--g2':    ('glassRaised',     'Raised glass, for a selected or elevated card.'),
    '--gl':    ('glassBorder',     'The .5px hairline around every glass surface.'),
    '--in':    ('inputFill',       'Input and inset fill.'),
    '--tx':    ('textPrimary',     'Primary text.'),
    '--t2':    ('textSecondary',   'Secondary text -- subtitles and supporting copy.'),
    '--t3':    ('textTertiary',    'Tertiary text -- eyebrows, timestamps, hints.'),
    '--hr':    ('divider',         'Hairline divider and empty progress track.'),
    '--sh':    ('shadow',          'Card shadow. Parsed into [AppShadows].'),
    '--bar':   ('tabBar',          'Floating tab bar background.'),
    '--fld':   ('fieldFill',       'Field fill, and the locked-achievement tile.'),
    '--pnl':   ('panel',           'Panel background, used by segmented controls.'),
    '--amb1':  ('ambient1',        'Page ambient glow, warm.'),
    '--amb2':  ('ambient2',        'Page ambient glow, gold.'),
    '--amb3':  ('ambient3',        'Page ambient glow, green.'),
    '--pamb1': ('phoneAmbient1',   'In-screen ambient glow, warm.'),
    '--pamb2': ('phoneAmbient2',   'In-screen ambient glow, red.'),
    '--pamb3': ('phoneAmbient3',   'In-screen ambient glow, gold.'),
}

# Values that are not colours and are handled elsewhere.
SKIP = {'--sh'}


def to_argb(css):
    """'#RRGGBB' or 'rgba(r,g,b,a)' -> a Dart 0xAARRGGBB literal."""
    css = css.strip()
    m = re.fullmatch(r'#([0-9A-Fa-f]{6})', css)
    if m:
        return '0xFF%s' % m.group(1).upper()

    m = re.fullmatch(r'rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)', css)
    if not m:
        raise SystemExit('cannot parse colour %r' % css)

    r, g, b = (int(m.group(i)) for i in (1, 2, 3))
    alpha = float(m.group(4))
    a = round(alpha * 255)
    return '0x%02X%02X%02X%02X' % (a, r, g, b)


def field(name, css, doc, indent='  '):
    return ('%s/// %s\n%s/// `%s`\n%sstatic const Color %s = Color(%s);\n'
            % (indent, doc, indent, css, indent, name, to_argb(css)))


def main():
    with open(TOKENS, encoding='utf-8') as fh:
        tokens = json.load(fh)

    dark, light = tokens['dark'], tokens['light']
    missing = set(NAMES) - set(dark) | set(NAMES) - set(light)
    if missing:
        raise SystemExit('tokens.json is missing: %s' % ', '.join(sorted(missing)))

    body = []
    body.append('''// GENERATED by tool/generate_theme.py from design/extracted/tokens.json.
// Do not edit by hand -- re-run the generator instead.
//
// The prototype defines its palette as two CSS variable maps with identical
// keys, so both themes are complete by construction: every surface, text tier,
// hairline and glow has a value in each.

import 'package:flutter/material.dart';

/// One theme's full palette.
///
/// Both [AppColors.dark] and [AppColors.light] are instances, so a widget
/// reads `colors.textSecondary` without asking which theme is active.
@immutable
class AppPalette {
  const AppPalette({''')

    for css, (name, _) in NAMES.items():
        if css in SKIP:
            continue
        body.append('    required this.%s,' % name)
    body.append('  });\n')

    for css, (name, doc) in NAMES.items():
        if css in SKIP:
            continue
        body.append('  /// %s' % doc)
        body.append('  final Color %s;' % name)
        body.append('')

    body.append('''  /// Resolve against a [BuildContext]'s brightness.
  static AppPalette of(BuildContext context) =>
      Theme.of(context).brightness == Brightness.dark
          ? AppColors.dark
          : AppColors.light;
}

/// The design's two palettes, plus the values that are theme-independent.
abstract final class AppColors {''')

    body.append('  /// Brand accent. `%s`' % tokens['accent'])
    body.append('  static const Color accent = Color(%s);' % to_argb(tokens['accent']))
    body.append('')
    body.append('  /// The accent alternates the design offers.')
    body.append('  static const List<Color> accentOptions = [')
    for option in tokens['accentOptions']:
        body.append('    Color(%s), // %s' % (to_argb(option), option))
    body.append('  ];')
    body.append('')
    body.append('''  /// The deeper end of the accent gradient used on primary buttons:
  /// `linear-gradient(160deg, --acc, #DE3A18)`.
  static const Color accentDeep = Color(0xFFDE3A18);

  /// Gold, used for XP badges and the first-place ring.
  static const Color gold = Color(0xFFF0B33C);

  /// Green, used for fasting dishes and completed quests.
  static const Color green = Color(0xFF2E9E5B);
''')

    for theme_name, table in (('dark', dark), ('light', light)):
        body.append('  /// The %s palette.' % theme_name)
        body.append('  static const AppPalette %s = AppPalette(' % theme_name)
        for css, (name, _) in NAMES.items():
            if css in SKIP:
                continue
            body.append('    %s: Color(%s), // %s' % (name, to_argb(table[css]), table[css]))
        body.append('  );')
        body.append('')

    body.append('}')

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(body).replace('\n\n\n', '\n\n') + '\n')

    count = len([c for c in NAMES if c not in SKIP])
    print('%s  %d colours x 2 themes' % (os.path.relpath(OUT, ROOT), count))


if __name__ == '__main__':
    sys.exit(main())
