// GENERATED by tool/generate_theme.py from design/extracted/tokens.json.
// Do not edit by hand -- re-run the generator instead.
//
// The prototype defines its palette as two CSS variable maps with identical
// keys, so both themes are complete by construction: every surface, text tier,
// hairline and glow has a value in each.

import 'package:flutter/material.dart';

/// One theme's full palette.
///
/// Both [AppColors.dark] and [AppColors.light] are instances, so a widget
/// reads `colors.textSecondary` without asking which theme is active.
@immutable
class AppPalette {
  const AppPalette({
    required this.background,
    required this.surface,
    required this.glass,
    required this.glassRaised,
    required this.glassBorder,
    required this.inputFill,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.divider,
    required this.tabBar,
    required this.fieldFill,
    required this.panel,
    required this.ambient1,
    required this.ambient2,
    required this.ambient3,
    required this.phoneAmbient1,
    required this.phoneAmbient2,
    required this.phoneAmbient3,
  });

  /// App background, behind the screen surface.
  final Color background;

  /// The screen surface itself.
  final Color surface;

  /// Glass fill -- the default card background.
  final Color glass;

  /// Raised glass, for a selected or elevated card.
  final Color glassRaised;

  /// The .5px hairline around every glass surface.
  final Color glassBorder;

  /// Input and inset fill.
  final Color inputFill;

  /// Primary text.
  final Color textPrimary;

  /// Secondary text -- subtitles and supporting copy.
  final Color textSecondary;

  /// Tertiary text -- eyebrows, timestamps, hints.
  final Color textTertiary;

  /// Hairline divider and empty progress track.
  final Color divider;

  /// Floating tab bar background.
  final Color tabBar;

  /// Field fill, and the locked-achievement tile.
  final Color fieldFill;

  /// Panel background, used by segmented controls.
  final Color panel;

  /// Page ambient glow, warm.
  final Color ambient1;

  /// Page ambient glow, gold.
  final Color ambient2;

  /// Page ambient glow, green.
  final Color ambient3;

  /// In-screen ambient glow, warm.
  final Color phoneAmbient1;

  /// In-screen ambient glow, red.
  final Color phoneAmbient2;

  /// In-screen ambient glow, gold.
  final Color phoneAmbient3;

  /// Resolve against a [BuildContext]'s brightness.
  static AppPalette of(BuildContext context) =>
      Theme.of(context).brightness == Brightness.dark
          ? AppColors.dark
          : AppColors.light;
}

/// The design's two palettes, plus the values that are theme-independent.
abstract final class AppColors {
  /// Brand accent. `#FF6A2B`
  static const Color accent = Color(0xFFFF6A2B);

  /// The accent alternates the design offers.
  static const List<Color> accentOptions = [
    Color(0xFFFF6A2B), // #FF6A2B
    Color(0xFFE23B2E), // #E23B2E
    Color(0xFFF0B33C), // #F0B33C
    Color(0xFF2E9E5B), // #2E9E5B
  ];

  /// The deeper end of the accent gradient used on primary buttons:
  /// `linear-gradient(160deg, --acc, #DE3A18)`.
  static const Color accentDeep = Color(0xFFDE3A18);

  /// Gold, used for XP badges and the first-place ring.
  static const Color gold = Color(0xFFF0B33C);

  /// Green, used for fasting dishes and completed quests.
  static const Color green = Color(0xFF2E9E5B);

  /// The dark palette.
  static const AppPalette dark = AppPalette(
    background: Color(0xFF0C0908), // #0C0908
    surface: Color(0xFF14100E), // #14100E
    glass: Color(0x12FFFFFF), // rgba(255,255,255,.07)
    glassRaised: Color(0x1FFFFFFF), // rgba(255,255,255,.12)
    glassBorder: Color(0x24FFFFFF), // rgba(255,255,255,.14)
    inputFill: Color(0x2EFFFFFF), // rgba(255,255,255,.18)
    textPrimary: Color(0xFFFFF6EE), // #FFF6EE
    textSecondary: Color(0x9EFFEEE2), // rgba(255,238,226,.62)
    textTertiary: Color(0x5CFFEEE2), // rgba(255,238,226,.36)
    divider: Color(0x1AFFFFFF), // rgba(255,255,255,.10)
    tabBar: Color(0x8C1E1611), // rgba(30,22,17,.55)
    fieldFill: Color(0x14FFFFFF), // rgba(255,255,255,.08)
    panel: Color(0x0DFFFFFF), // rgba(255,255,255,.05)
    ambient1: Color(0x4CFF6A2B), // rgba(255,106,43,.30)
    ambient2: Color(0x33F0B33C), // rgba(240,179,60,.20)
    ambient3: Color(0x242E9E5B), // rgba(46,158,91,.14)
    phoneAmbient1: Color(0x4CFF6A2B), // rgba(255,106,43,.30)
    phoneAmbient2: Color(0x38C0301C), // rgba(192,48,28,.22)
    phoneAmbient3: Color(0x29F0B33C), // rgba(240,179,60,.16)
  );

  /// The light palette.
  static const AppPalette light = AppPalette(
    background: Color(0xFFEDE3D6), // #EDE3D6
    surface: Color(0xFFFCF7F0), // #FCF7F0
    glass: Color(0x99FFFFFF), // rgba(255,255,255,.60)
    glassRaised: Color(0xE0FFFFFF), // rgba(255,255,255,.88)
    glassBorder: Color(0xE6FFFFFF), // rgba(255,255,255,.9)
    inputFill: Color(0xFFFFFFFF), // rgba(255,255,255,1)
    textPrimary: Color(0xFF1D120C), // #1D120C
    textSecondary: Color(0x941D120C), // rgba(29,18,12,.58)
    textTertiary: Color(0x571D120C), // rgba(29,18,12,.34)
    divider: Color(0x1A1D120C), // rgba(29,18,12,.10)
    tabBar: Color(0x9EFFFFFF), // rgba(255,255,255,.62)
    fieldFill: Color(0xBFFFFFFF), // rgba(255,255,255,.75)
    panel: Color(0x8CFFFFFF), // rgba(255,255,255,.55)
    ambient1: Color(0x42FF6A2B), // rgba(255,106,43,.26)
    ambient2: Color(0x57F0B33C), // rgba(240,179,60,.34)
    ambient3: Color(0x292E9E5B), // rgba(46,158,91,.16)
    phoneAmbient1: Color(0x33FF6A2B), // rgba(255,106,43,.20)
    phoneAmbient2: Color(0x42F0B33C), // rgba(240,179,60,.26)
    phoneAmbient3: Color(0x1F2E9E5B), // rgba(46,158,91,.12)
  );
}
